### PR TITLE
D&D Beyond, Including Subclass spells

### PR DESCRIPTION
**Pull request by oshinowo-stephen**
## Describe your changes

- Added `getSubclassSpells`
- Added a development server using [ExpressJS](https://expressjs.com/)
- Included `subclassDefinition` in `DbdClass`
- Included `campaign` in `DbdCharacter`
- Changed `convertSpells`, `convertSpell` and `convertFile`

## D&D Beyond character link

Tried these characters:

https://www.dndbeyond.com/characters/96625992
https://www.dndbeyond.com/characters/98857388
https://www.dndbeyond.com/characters/99603501
https://www.dndbeyond.com/characters/102523122

Output came out expected with included spells from class and subclasses

## Pre-review checklist

- [x] I have added a description of my changes
- [x] I have added a link to a D&D Beyond character that can be used to test these changes
- [x] I have read the [contributing guidelines](CONTRIBUTING.md)
- [x] I agree to the [code of conduct](CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by thatbudakguy — COMMENTED** [review]
it's super frustrating that DDB divides up character information across multiple undocumented APIs. is there a way to know how many other APIs there are that we may want or need to end up calling to form the full data for a character?

bringing in a bunch of dependencies in order to run a dev server to get around CORS to make requests seems less than ideal. i'm not sure what the implications for alchemy itself are. 

architecturally, i'd prefer it if the conversion and data-fetching parts of the library were separated — make however many requests are required, then pass a fully-formed data object to the converter, which operates synchronously and doesn't need to request more data. we're in an awkward position, though.

@ioveracker curious to hear what you think of this situation.

**Comment by oshinowo-stephen** [comment]
> it's super frustrating that DDB divides up character information across multiple undocumented APIs. is there a way to know how many other APIs there are that we may want or need to end up calling to form the full data for a character?

I've searched but nothing really caught my attention, finding this endpoint was a task as well. In my experience, it seems that we would have to bounce to different APIs that DDB provides you...

**Comment by MarkJPerry** [comment]
Just been looking at this problem with krsr from the Discord. I think it's maybe easier/simpler to just scrape all the "known-spells" json for every class into static files and include them in the repo. Then we can just use those in the conversion process.

The only downside having to do some periodic updates to those files.

**Comment by oshinowo-stephen** [comment]
> Just been looking at this problem with krsr from the Discord. I think it's maybe easier/simpler to just scrape all the "known-spells" json for every class into static files and include them in the repo. Then we can just use those in the conversion process.
> 
> The only downside having to do some periodic updates to those files.

Agreed, I would try to implement this change in this current branch later this week, or I can allow someone else to take care of it.

**Comment by ioveracker** [comment]
Another potential option is to send the spells in by name. Alchemy will match them against known spells from the SRD universe during import.

**Comment by thatbudakguy** [comment]
Seems like a good place to start would be trying to figure out what types of values DDB is looking for as the `classId` param in the API URL (https://character-service.dndbeyond.com/character/v5/game-data/always-prepared-spells).

Could we start from `classId=1` and level 20 and just "crawl" it a little bit? Are these long numeric IDs like `entityId`s, so we need another way?

**Comment by ioveracker** [comment]
Also, if we need to hit another API to get some additional spells for the character, we can and should do that on the Alchemy app side of things

**Comment by thatbudakguy** [comment]
I wrote a very stupid shell script to "crawl" this API and look for valid `classId`s. Starting from zero, a handful turned out to have valid output (I stopped at 1000):
```
19, 21, 29, 30, 31, 32, 33, 34, 41, 42, 65, 66, 67, 68, 69, 70, 71, 72, 74, 78, 84, 85, 87, 98, 106, 107, 123, 126, 223, 600, 760, 973
```
You can check the actual subclass spell list for one of these (if you have `jq`) with:
```sh
curl -s "https://character-service.dndbeyond.com/character/v5/game-data/always-prepared-spells?classId=70&classLevel=20" | jq '.data[].definition.name'
```
Which will return e.g.
```sh
"Stoneskin"
"Lightning Bolt"
"Wall of Stone"
"Meld into Stone"
"Passwall"
"Spider Climb"
"Spike Growth"
"Stone Shape"
```
I can't tell if the `classId` value space is bounded. It seems like it might include every subclass created by _anyone_ on DDB (I tried with a homebrew subclass ID, which was much higher, and it seemed to work). If this is in fact the case, pre-downloading the output doesn't seem workable.

**Comment by oshinowo-stephen** [comment]
> I wrote a very stupid shell script to "crawl" this API and look for valid `classId`s. Starting from zero, a handful turned out to have valid output (I stopped at 1000):
> 
> ```
> 19, 21, 29, 30, 31, 32, 33, 34, 41, 42, 65, 66, 67, 68, 69, 70, 71, 72, 74, 78, 84, 85, 87, 98, 106, 107, 123, 126, 223, 600, 760, 973
> ```
> 
> You can check the actual subclass spell list for one of these (if you have `jq`) with:
> 
> ```shell
> curl -s "https://character-service.dndbeyond.com/character/v5/game-data/always-prepared-spells?classId=70&classLevel=20" | jq '.data[].definition.name'
> ```
> 
> Which will return e.g.
> 
> ```shell
> "Stoneskin"
> "Lightning Bolt"
> "Wall of Stone"
> "Meld into Stone"
> "Passwall"
> "Spider Climb"
> "Spike Growth"
> "Stone Shape"
> ```
> 
> I can't tell if the `classId` value space is bounded. It seems like it might include every subclass created by _anyone_ on DDB (I tried with a homebrew subclass ID, which was much higher, and it seemed to work). If this is in fact the case, pre-downloading the output doesn't seem workable.

thank you for doing this, i was going do it myself, but the iteration seems to go all over 1000, but i'll assume those were homebrew subclasses and such, so luckily all we need to is match the `subclassDefiniton` id with one form this list, and just return the bounded spell...

also pre-downloading the output is plausible but unsure if it's effcient the file would be over mainly 90000 lines of per subclasses, as i was iterating over 5000 (cause i was unsure which ones were supposed to go in there), it stopped over 5206 and it seems it could've kept going

**Comment by oshinowo-stephen** [comment]
> Also, if we need to hit another API to get some additional spells for the character, we can and should do that on the Alchemy app side of things vs. here in the library

if we could, other than making the user handle this is to just make the server-side requests upon the API and the user would just flood in the character data, other than those suggestions i'm unsure how to continue. thoughts?

**Comment by thatbudakguy** [comment]
> just make the server-side requests upon the API and the user would just flood in the character data

I think this is what we should do. Basically, I'd like to keep what you have for `getSubclassSpells` currently, but move the fetching part into a separate script whose job is to generate the fully-formed character JSON. So, there should be almost no changes to `convert.ts`.

We'll rely on @ioveracker to do basically the same thing on the Alchemy side, so that the character JSON is always expected to have the subclass spells already added to it at the time we call `convertCharacter`.

**Comment by oshinowo-stephen** [comment]
> I think this is what we should do. Basically, I'd like to keep what you have for `getSubclassSpells` currently, but move the fetching part into a separate script whose job is to generate the fully-formed character JSON. So, there should be almost no changes to `convert.ts`.

actually just editing the original script of the: https://github.com/alchemyrpg/ddb2alchemy/blob/main/src/bookmarklet.js

we can just make two requests upon the character-service and the game-data-service and just include the spells into the object, which personally I don't like since we're going to edit the exported object, but meh

``
(()=>{var s=window.location.toString().match(/https:\/\/www\.dndbeyond\.com\/characters\/(\d+)/),d="https://character-service.dndbeyond.com/character/v5/character",r="https://character-service.dndbeyond.com/character/v5/game-data",i=s[1],l=(a,e)=>{let t=document.createElement("a");t.setAttribute("href","data:application/json;charset=utf-8,"+encodeURIComponent(e)),t.setAttribute("download",a),t.style.display="none",document.body.appendChild(t),t.click(),document.body.removeChild(t)};(async()=>{if(s){let a=await fetch(`${d}/${i}`),{data:e}=await a.json();for(let{level:t,subclassDefinition:c}of e.classes){if(!c)continue;let o=await fetch(`${r}/always-prepared-spells?classLevel=${t}&classId=${c.id}&campaign=${e.campaign?e.campaign.id:void 0}`),{data:n}=await o.json();n.length!==0&&e.classSpells.push({entityTypeId:0,characterClassId:c.id,spells:n})}l(`${e.name}.json`,JSON.stringify(e))}})().catch(console.error);})();
```

this current script basically fetches the character and spells, then export the always-prep-spells into the classSpells

**Comment by thatbudakguy** [comment]
that would work for me, but does it actually work? I thought that we couldn't do that client-side because of CORS issues, so we would have to call out to `curl` or use some other server-side strategy.

**Comment by oshinowo-stephen** [comment]
> that would work for me, but does it actually work? I thought that we couldn't do that client-side because of CORS issues, so we would have to call out to `curl` or use some other server-side strategy.

we couldn't do in the application itself, but the user can just spit this in their browser console and then download the JSON file

**Comment by thatbudakguy** [comment]
@oshinowo-stephen can you open a new PR with just the changes to bookmarklet.js? I don't think any other file should be changed. that'll make it easier to review; this PR is kind of a mess at this point

**Pull request closed without merging**
